version: '3.7'

services:

  postgres:
    container_name: postgres_casadocodigo
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casadocodigo
